In [1]:
import requests
import pandas as pd
import sqlite3
from sqlalchemy import create_engine

In [2]:
def get_weather(location):
    l = []
    for i in location:
        url = "https://weatherapi-com.p.rapidapi.com/current.json"

        querystring = {"q":i}

        headers = {
        "x-rapidapi-key": "",
        "x-rapidapi-host": "weatherapi-com.p.rapidapi.com"
    }

        response = requests.get(url, headers=headers, params=querystring)
        #print(response.json())
        l.append(response.json())
    #print(l)
    df = pd.json_normalize(l)
    return df

def write_to_db(location):
    df= get_weather(location)
    engine = create_engine('sqlite:///weather.db')
    df.to_sql('weather_data', engine, if_exists='append', index=False)
    print('sekmingai irasyti duomenys i duomenu baze')

In [3]:
write_to_db(['Avizieniai'])

sekmingai irasyti duomenys i duomenu baze

In [4]:
con = sqlite3.connect("weather.db")

In [5]:
cur = con.cursor()

In [ ]:
res = cur.execute("""SELECT * FROM weather_data""")
data = res.fetchall()

In [ ]:
columns = [description[0] for description in cur.description]

# Create a DataFrame

dff = pd.DataFrame(data, columns=columns)

# Display the DataFrame
dff

### Extra code

In [12]:
cur.execute("""CREATE TABLE weather_data('location.name', 'location.region', 
            'location.country', 'location.lat', 'location.lon', 'location.tz_id', 'location.localtime_epoch','location.localtime', 'current.last_updated_epoch', 'current.last_updated', 'current.temp_c', 'current.temp_f','current.is_day', 'current.condition.text', 'current.condition.icon',
       'current.condition.code', 'current.wind_mph', 'current.wind_kph',
       'current.wind_degree', 'current.wind_dir', 'current.pressure_mb',
       'current.pressure_in', 'current.precip_mm', 'current.precip_in',
       'current.humidity', 'current.cloud', 'current.feelslike_c',
       'current.feelslike_f', 'current.windchill_c', 'current.windchill_f',
       'current.heatindex_c', 'current.heatindex_f', 'current.dewpoint_c',
       'current.dewpoint_f', 'current.vis_km', 'current.vis_miles',
       'current.uv', 'current.gust_mph', 'current.gust_kph')""")

In [44]:
con.commit()

In [7]:
data

[('Moletai',
  'Utenos Apskritis',
  'Lithuania',
  55.15,
  25.24,
  'Europe/Vilnius',
  1722858415,
  '2024-08-05 14:46',
  1722858300,
  '2024-08-05 14:45',
  21.8,
  71.2,
  1,
  'Overcast',
  '//cdn.weatherapi.com/weather/64x64/day/122.png',
  1009,
  5.1,
  8.3,
  147,
  'SSE',
  1009.0,
  29.79,
  0.0,
  0.0,
  63,
  89,
  21.8,
  71.2,
  21.8,
  71.2,
  24.5,
  76.2,
  14.4,
  57.9,
  10.0,
  6.0,
  5.0,
  6.5,
  10.4),
 ('Anyksciai',
  'Panevezio Apskritis',
  'Lithuania',
  55.53,
  25.07,
  'Europe/Vilnius',
  1722860439,
  '2024-08-05 15:20',
  1722860100,
  '2024-08-05 15:15',
  19.7,
  67.4,
  1,
  'Patchy rain nearby',
  '//cdn.weatherapi.com/weather/64x64/day/176.png',
  1063,
  2.2,
  3.6,
  154,
  'SSE',
  1009.0,
  29.8,
  0.11,
  0.0,
  73,
  77,
  19.7,
  67.4,
  19.7,
  67.4,
  19.7,
  67.4,
  14.7,
  58.4,
  10.0,
  6.0,
  4.0,
  6.7,
  10.8),
 ('Birstonas',
  'Alytaus Apskritis',
  'Lithuania',
  54.62,
  24.03,
  'Europe/Vilnius',
  1722862800,
  '2024-08-05 16:00',
  1722862800,
  '2024-08-05 16:00',
  21.3,
  70.4,
  1,
  'Light rain shower',
  '//cdn.weatherapi.com/weather/64x64/day/353.png',
  1240,
  2.2,
  3.6,
  227,
  'SW',
  1008.0,
  29.78,
  1.09,
  0.04,
  72,
  67,
  21.3,
  70.4,
  21.3,
  70.4,
  24.4,
  75.9,
  16.0,
  60.7,
  10.0,
  6.0,
  5.0,
  3.4,
  5.5),
 ('Birstonas',
  'Alytaus Apskritis',
  'Lithuania',
  54.62,
  24.03,
  'Europe/Vilnius',
  1722863989,
  '2024-08-05 16:19',
  1722863700,
  '2024-08-05 16:15',
  21.3,
  70.4,
  1,
  'Light rain shower',
  '//cdn.weatherapi.com/weather/64x64/day/353.png',
  1240,
  2.2,
  3.6,
  227,
  'SW',
  1008.0,
  29.78,
  1.09,
  0.04,
  72,
  67,
  21.3,
  70.4,
  21.3,
  70.4,
  24.4,
  75.9,
  16.0,
  60.7,
  10.0,
  6.0,
  5.0,
  3.4,
  5.5),
 ('Birzai',
  'Panevezio Apskritis',
  'Lithuania',
  56.2,
  24.75,
  'Europe/Vilnius',
  1722863992,
  '2024-08-05 16:19',
  1722863700,
  '2024-08-05 16:15',
  22.2,
  72.0,
  1,
  'Patchy rain nearby',
  '//cdn.weatherapi.com/weather/64x64/day/176.png',
  1063,
  3.6,
  5.8,
  232,
  'SW',
  1009.0,
  29.79,
  0.26,
  0.01,
  64,
  79,
  24.6,
  76.4,
  22.2,
  72.0,
  24.6,
  76.4,
  15.1,
  59.2,
  9.0,
  5.0,
  5.0,
  4.8,
  7.7),
 ('Klaipeda',
  'Klaipedos Apskritis',
  'Lithuania',
  55.72,
  21.12,
  'Europe/Vilnius',
  1722863995,
  '2024-08-05 16:19',
  1722863700,
  '2024-08-05 16:15',
  19.2,
  66.6,
  1,
  'Patchy light drizzle',
  '//cdn.weatherapi.com/weather/64x64/day/263.png',
  1150,
  9.6,
  15.5,
  327,
  'NNW',
  1010.0,
  29.82,
  0.16,
  0.01,
  81,
  83,
  19.2,
  66.6,
  19.2,
  66.6,
  19.2,
  66.6,
  15.9,
  60.6,
  5.0,
  3.0,
  4.0,
  12.8,
  20.5),
 ('Prienai',
  'Kauno Apskritis',
  'Lithuania',
  54.63,
  23.95,
  'Europe/Vilnius',
  1722864155,
  '2024-08-05 16:22',
  1722863700,
  '2024-08-05 16:15',
  21.3,
  70.4,
  1,
  'Light rain shower',
  '//cdn.weatherapi.com/weather/64x64/day/353.png',
  1240,
  2.2,
  3.6,
  227,
  'SW',
  1008.0,
  29.78,
  1.09,
  0.04,
  72,
  67,
  21.3,
  70.4,
  21.3,
  70.4,
  24.4,
  75.9,
  16.0,
  60.7,
  10.0,
  6.0,
  5.0,
  3.4,
  5.5),
 ('Vilkaviskis',
  'Marijampoles Apskritis',
  'Lithuania',
  54.65,
  23.03,
  'Europe/Vilnius',
  1722864906,
  '2024-08-05 16:35',
  1722864600,
  '2024-08-05 16:30',
  21.7,
  71.1,
  1,
  'Light rain shower',
  '//cdn.weatherapi.com/weather/64x64/day/353.png',
  1240,
  5.1,
  8.3,
  354,
  'N',
  1008.0,
  29.78,
  0.53,
  0.02,
  66,
  58,
  21.7,
  71.1,
  21.7,
  71.1,
  24.5,
  76.1,
  15.2,
  59.3,
  10.0,
  6.0,
  5.0,
  6.5,
  10.4),
 ('Avizieniai',
  'Vilniaus Apskritis',
  'Lithuania',
  54.7667,
  25.1833,
  'Europe/Vilnius',
  1739371427,
  '2025-02-12 16:43',
  1739370600,
  '2025-02-12 16:30',
  -6.8,
  19.8,
  1,
  'Sunny',
  '//cdn.weatherapi.com/weather/64x64/day/113.png',
  1000,
  4.0,
  6.5,
  166,
  'SSE',
  1030.0,
  30.42,
  0.0,
  0.0,
  79,
  0,
  -10.1,
  13.9,
  -4.8,
  23.5,
  -2.2,
  28.1,
  -8.8,
  16.1,
  10.0,
  6.0,
  0.1,
  5.7,
  9.2)]

In [8]:
columns = [description[0] for description in cur.description]

# Create a DataFrame

dff = pd.DataFrame(data, columns=columns)

# Display the DataFrame
dff

,location.name,location.region,location.country,location.lat,location.lon,location.tz_id,location.localtime_epoch,location.localtime,current.last_updated_epoch,current.last_updated,...,current.windchill_f,current.heatindex_c,current.heatindex_f,current.dewpoint_c,current.dewpoint_f,current.vis_km,current.vis_miles,current.uv,current.gust_mph,current.gust_kph
0,Moletai,Utenos Apskritis,Lithuania,55.1500,25.2400,Europe/Vilnius,1722858415,2024-08-05 14:46,1722858300,2024-08-05 14:45,...,71.2,24.5,76.2,14.4,57.9,10.0,6.0,5.0,6.5,10.4
1,Anyksciai,Panevezio Apskritis,Lithuania,55.5300,25.0700,Europe/Vilnius,1722860439,2024-08-05 15:20,1722860100,2024-08-05 15:15,...,67.4,19.7,67.4,14.7,58.4,10.0,6.0,4.0,6.7,10.8
2,Birstonas,Alytaus Apskritis,Lithuania,54.6200,24.0300,Europe/Vilnius,1722862800,2024-08-05 16:00,1722862800,2024-08-05 16:00,...,70.4,24.4,75.9,16.0,60.7,10.0,6.0,5.0,3.4,5.5
3,Birstonas,Alytaus Apskritis,Lithuania,54.6200,24.0300,Europe/Vilnius,1722863989,2024-08-05 16:19,1722863700,2024-08-05 16:15,...,70.4,24.4,75.9,16.0,60.7,10.0,6.0,5.0,3.4,5.5
4,Birzai,Panevezio Apskritis,Lithuania,56.2000,24.7500,Europe/Vilnius,1722863992,2024-08-05 16:19,1722863700,2024-08-05 16:15,...,72.0,24.6,76.4,15.1,59.2,9.0,5.0,5.0,4.8,7.7
5,Klaipeda,Klaipedos Apskritis,Lithuania,55.7200,21.1200,Europe/Vilnius,1722863995,2024-08-05 16:19,1722863700,2024-08-05 16:15,...,66.6,19.2,66.6,15.9,60.6,5.0,3.0,4.0,12.8,20.5
6,Prienai,Kauno Apskritis,Lithuania,54.6300,23.9500,Europe/Vilnius,1722864155,2024-08-05 16:22,1722863700,2024-08-05 16:15,...,70.4,24.4,75.9,16.0,60.7,10.0,6.0,5.0,3.4,5.5
7,Vilkaviskis,Marijampoles Apskritis,Lithuania,54.6500,23.0300,Europe/Vilnius,1722864906,2024-08-05 16:35,1722864600,2024-08-05 16:30,...,71.1,24.5,76.1,15.2,59.3,10.0,6.0,5.0,6.5,10.4
8,Avizieniai,Vilniaus Apskritis,Lithuania,54.7667,25.1833,Europe/Vilnius,1739371427,2025-02-12 16:43,1739370600,2025-02-12 16:30,...,23.5,-2.2,28.1,-8.8,16.1,10.0,6.0,0.1,5.7,9.2

In [41]:
juskos_koordinates = {"q":'55.53 25.067'}

In [25]:
query = "Select * from weather_data"

In [27]:
from sqlalchemy import inspect

In [30]:

insp = inspect(engine)

columns_table = insp.get_columns('weather_data') #schema is optional


for c in columns_table :
    print(c['name'], c['type'])

location.name NULL
location.region NULL
location.country NULL
location.lat NULL
location.lon NULL
location.tz_id NULL
location.localtime_epoch NULL
location.localtime NULL
current.last_updated_epoch NULL
current.last_updated NULL
current.temp_c NULL
current.temp_f NULL
current.is_day NULL
current.condition.text NULL
current.condition.icon NULL
current.condition.code NULL
current.wind_mph NULL
current.wind_kph NULL
current.wind_degree NULL
current.wind_dir NULL
current.pressure_mb NULL
current.pressure_in NULL
current.precip_mm NULL
current.precip_in NULL
current.humidity NULL
current.cloud NULL
current.feelslike_c NULL
current.feelslike_f NULL
current.windchill_c NULL
current.windchill_f NULL
current.heatindex_c NULL
current.heatindex_f NULL
current.dewpoint_c NULL
current.dewpoint_f NULL
current.vis_km NULL
current.vis_miles NULL
current.uv NULL
current.gust_mph NULL
current.gust_kph NULL

In [18]:
from sqlalchemy import create_engine

In [19]:
engine = create_engine('sqlite:///weather.db')

In [47]:
engine = create_engine('sqlite:///weather.db')
df.to_sql('weather_data', engine, if_exists='append', index=False)

1

In [42]:

url = "https://weatherapi-com.p.rapidapi.com/current.json"

querystring = {"q":"55.15 25.24"}

headers = {
	"x-rapidapi-key": "a705f8fcafmsh9a2dc799e683468p18d984jsn329cf1073e42",
	"x-rapidapi-host": "weatherapi-com.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=juskos_koordinates)

print(response.json())

{'location': {'name': 'Anyksciai', 'region': 'Panevezio Apskritis', 'country': 'Lithuania', 'lat': 55.53, 'lon': 25.07, 'tz_id': 'Europe/Vilnius', 'localtime_epoch': 1722860439, 'localtime': '2024-08-05 15:20'}, 'current': {'last_updated_epoch': 1722860100, 'last_updated': '2024-08-05 15:15', 'temp_c': 19.7, 'temp_f': 67.4, 'is_day': 1, 'condition': {'text': 'Patchy rain nearby', 'icon': '//cdn.weatherapi.com/weather/64x64/day/176.png', 'code': 1063}, 'wind_mph': 2.2, 'wind_kph': 3.6, 'wind_degree': 154, 'wind_dir': 'SSE', 'pressure_mb': 1009.0, 'pressure_in': 29.8, 'precip_mm': 0.11, 'precip_in': 0.0, 'humidity': 73, 'cloud': 77, 'feelslike_c': 19.7, 'feelslike_f': 67.4, 'windchill_c': 19.7, 'windchill_f': 67.4, 'heatindex_c': 19.7, 'heatindex_f': 67.4, 'dewpoint_c': 14.7, 'dewpoint_f': 58.4, 'vis_km': 10.0, 'vis_miles': 6.0, 'uv': 4.0, 'gust_mph': 6.7, 'gust_kph': 10.8}}

In [11]:
print(response.json

In [43]:
df = pd.json_normalize(response.json())
#df['current.temp_c']
df

,location.name,location.region,location.country,location.lat,location.lon,location.tz_id,location.localtime_epoch,location.localtime,current.last_updated_epoch,current.last_updated,...,current.windchill_f,current.heatindex_c,current.heatindex_f,current.dewpoint_c,current.dewpoint_f,current.vis_km,current.vis_miles,current.uv,current.gust_mph,current.gust_kph
0,Anyksciai,Panevezio Apskritis,Lithuania,55.53,25.07,Europe/Vilnius,1722860439,2024-08-05 15:20,1722860100,2024-08-05 15:15,...,67.4,19.7,67.4,14.7,58.4,10.0,6.0,4.0,6.7,10.8

In [9]:
df.columns

Index(['location.name', 'location.region', 'location.country', 'location.lat',
       'location.lon', 'location.tz_id', 'location.localtime_epoch',
       'location.localtime', 'current.last_updated_epoch',
       'current.last_updated', 'current.temp_c', 'current.temp_f',
       'current.is_day', 'current.condition.text', 'current.condition.icon',
       'current.condition.code', 'current.wind_mph', 'current.wind_kph',
       'current.wind_degree', 'current.wind_dir', 'current.pressure_mb',
       'current.pressure_in', 'current.precip_mm', 'current.precip_in',
       'current.humidity', 'current.cloud', 'current.feelslike_c',
       'current.feelslike_f', 'current.windchill_c', 'current.windchill_f',
       'current.heatindex_c', 'current.heatindex_f', 'current.dewpoint_c',
       'current.dewpoint_f', 'current.vis_km', 'current.vis_miles',
       'current.uv', 'current.gust_mph', 'current.gust_kph'],
      dtype='object')